apiVersion: v1
kind: ResourceQuota
metadata:
  name: ${var.k8s_deployment_name}-quota
  namespace: ${var.k8s_namespace}
  labels:
    app.kubernetes.io/name: ${var.project_name}
    app.kubernetes.io/instance: ${var.k8s_project_instance}
    app.kubernetes.io/version: "${var.project_revision}"
    app.kubernetes.io/part-of: ${var.project_organization}
    app.kubernetes.io/managed-by: ${var.tool_name}
    environment: ${var.environment}
spec:
  hard:
    requests.memory: "${var.k8s_quota_requests_memory}"
    requests.cpu: "${var.k8s_quota_requests_cpu}"
    
    limits.memory: "${var.k8s_quota_limits_memory}"
    limits.cpu: "${var.k8s_quota_limits_cpu}"
    
    pods: "${var.k8s_quota_pods}"
    services: "${var.k8s_quota_services}"
    
    persistentvolumeclaims: "${var.k8s_quota_pvc}"
    requests.storage: "${var.k8s_quota_storage}"
