apiVersion: v1
kind: Service
metadata:
  name: ${var.k8s_deployment_name}-service
  namespace: ${var.k8s_namespace}
  labels:
    app.kubernetes.io/name: ${var.project_name12}
    app.kubernetes.io/instance: ${var.k8s_project_instance}
    app.kubernetes.io/version: ${var.project_version}
    app.kubernetes.io/part-of: ${var.project_organization}
    app.kubernetes.io/managed-by: ${var.KeyToolName}
    environment: ${var.environment}
spec:
  type: ClusterIP
  ports:
  - port: ${var.k8s_service_port}
    targetPort: ${var.app_port}
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: ${var.project_name12}
    app.kubernetes.io/part-of: ${var.project_organization}
    environment: ${var.environment}
